server:
  port: 8080

spring:
  application:
    name: spring-boot-examples

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

  sql:
    init:
      mode: always