server:
  port: 8080

spring:
  application:
    name: spring-boot-examples

  datasource:
    url: jdbc:h2:mem:tacocloud
    driver-class-name: org.h2.Driver
    username: sa  # Default username for H2
    password:  # No password for H2 by default
    name: tacocloud
    generate-unique-name: false

  h2:
    console:
      enabled: true  # Enable H2 database console at /h2-console
