server:
  port: 8080

spring:
  application:
    name: spring-boot-examples

  cassandra:
    local-datacenter: datacenter1
    schema-action: recreate
    keyspace-name: tacocloud
    username: cassandra
    password: cassandra